# Generated by Django 4.0.6 on 2022-07-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
    ]
