# Generated by Django 4.0.6 on 2022-07-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='name',
            field=models.CharField(default='New Item', max_length=50),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
